// Define the core data structure for a Product in the application.
// We allow 'id' to be null for products that haven't been saved to the database yet (e.g., in the modal).
// Match these to your PostgreSQL columns
export interface Product {
    ItemID: number;
    Name: string;
    Price: number;
    StockLevel: number;
    CategoryName: string; // From the join in getAllProducts
    LowStockThreshold: number;
    IsActive: boolean;
    // Add other fields as needed
}

// --- Product Payload Interface (for creating a NEW product) ---
// Since the ID is generated by the DB, it's optional on creation.
export interface CreateProduct {
    id?: number; // Optional for creation
    name: string;
    description?: string;
    price: number;
    // When creating, we might send initial stock, but StockLevel isn't sent directly
    // Instead, we might send InitialStock for the movement handler.
    initialStock?: number; 
    categoryId: number; 
    lowStockThreshold?: number;
}
export interface Category {
    CategoryID: number;
    Name: string;
}

